publishes ci tests results

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -47,6 +47,10 @@ jobs:
           path: autodoc/schemaspy-report.zip
           retention-days: 90       
 
+      - name: Push Docker images (all tags)
+        run: |
+          cd .github/workflows
+          bash dockerpush.sh
 
       - name: Run Ci
         run: |
@@ -55,7 +59,9 @@ jobs:
           chmod -R 777 target
           docker compose up --exit-code-from tester
 
-      - name: Push Docker images (all tags)
-        run: |
-          cd .github/workflows
-          bash dockerpush.sh
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/ci-tests/target/TESTS-*.xml'
+
